apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: app-image
  newName: pokotyan/k8s-request-counter-emitter
  newTag: 35308ca6d3a5e3c91ad8154d7f944f34a96370df
