apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/app
- ../../base/redis
images:
- name: app-image
  newName: pokotyan/k8s-request-counter-emitter
  newTag: 3530e9ab59ec2c1b292a30bdd96b3da6f91a5bf3
