apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/app
- ../../base/redis
images:
- name: app-image
  newName: pokotyan/k8s-request-counter-emitter
  newTag: 95fcc68cacc0f5967b6c05da393f5d632946353d
