apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: app-image
  newName: pokotyan/k8s-request-counter-emitter
  newTag: 8f01ea7cfd88df008795f988297ad890e7b1ca12
