apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: pokoytan/k8s-request-counter-emitter
      context: ./
      docker:
        dockerfile: ./Dockerfile
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
profiles:
  - name: local
    deploy:
      kustomize:
        paths: ["k8s/kustomize/overlays/local"]
