apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          command: ["/bin/bash", "-c", "nginx -g 'daemon off;'"] # can not modify /etc/nginx/conf.d/default.conf (read-only file system?) を防止
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-default-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: app-container
          image: k8s-request-counter-emitter:latest
          command: ["./main"]
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: nginx-default-config
          configMap:
            name: nginx-default-configmap
        - name: nginx-nginx-config
          configMap:
            name: nginx-nginx-configmap
