apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-configmap
  namespace: default
data:
  default.conf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            proxy_pass   http://localhost:8080;
        }
    }
