apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: k8s-request-counter-emitter
      context: ./
      docker:
        dockerfile: ./Dockerfile
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - k8s/app/nginx-default-configmap.yml
      - k8s/app/nginx-nginx-configmap.yml
      - k8s/app/deployment.yml
      - k8s/app/service.yml
      - k8s/app/ingress.yml
