apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: slack-notification
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "POST"
            - "--data-urlencode"
            - "payload={\"channel\": \"#gitops\", \"username\": \"hello\", \"text\": \"App Sync succeeded\", \"icon_emoji\": \":ghost:\"}"
            - "https://hooks.slack.com/services/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"
          env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: slackWebhookUrl
      restartPolicy: Never
  backoffLimit: 2
