name: ci

on:
  push:
    branches: main

jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |-
          docker build --tag pokotyan/k8s-request-counter-emitter:${GITHUB_SHA} .

      - name: Push Image
        run: |-
          docker push pokotyan/k8s-request-counter-emitter:${GITHUB_SHA}
  deploy-local:
    runs-on: ubuntu-latest
    needs: push-image-to-docker-hub
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod +x ./kustomize

      - name: Set up Git
        run: |
          git config --local user.email "tomohiro_soga@yahoo.co.jp"
          git config --local user.name "pokotyan"

      - name: Commit after Build manifest
        run: |
          bash ./k8s/kustomize/overlays/local/build.sh pokotyan/k8s-request-counter-emitter:${GITHUB_SHA}
          git commit -am "Update image to pokotyan/k8s-request-counter-emitter:$GITHUB_SHA"
          git pull
          git push origin main