name: ci

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build image
        run: |-
          docker build --tag "pokotyan/k8s-request-counter-emitter":"${GITHUB_REF##*/}" .
      - name: push image
        run: |-
          docker push "pokotyan/k8s-request-counter-emitter":"${GITHUB_REF##*/}"